services:
  incident-checker:
    container_name: incident-checker
    image: judelhaye/incident-checker:latest
    ports:
      - "5042:5042"
    volumes:
      - incident_data:/app/data
    restart: unless-stopped

volumes:
  incident_data: